//JAVASCRIPT EXECUTION CONTEXT
//GLOBAL EXECUTION CONTEXT
//FUNCTION EXECUTION CONTEXT

//THERE ARE TWO PHASES IN EXECUTION CONTEXT ,THEY ARE MEMORY ALLOCATION PHASE AND CODE EXECUTION PHASE
//MEMORY ALLOCATION PHASE
//IN THIS PHASE THE JAVASCRIPT ENGINE ALLOCATES MEMORY FOR VARIABLES AND FUNCTIONS
//CODE EXECUTION PHASE
//IN THIS PHASE THE JAVASCRIPT ENGINE EXECUTES THE CODE LINE BY LINE